parameters:
#    trnkt_core.example.class: Trnkt\CoreBundle\Example

services:
#    trnkt_core.example:
#        class: %trnkt_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
